#!/usr/bin/env bash
# CPM — Generate TRUTH.md (single source of truth)
# Reads all summaries + live git state → writes TRUTH.md

set -eu
# Note: no pipefail — `head -N` after sorts triggers SIGPIPE in upstream sort/uniq

WORKSPACE="$(cd "$(dirname "$0")/.." && pwd)"
SUMMARY_DIR="$WORKSPACE/memory/summaries"
TRUTH="$WORKSPACE/TRUTH.md"

source "$WORKSPACE/scripts/detect-projects.sh"
PROJECTS=("${CPM_PROJECTS[@]}")

LAST_UPDATED=$(date "+%Y-%m-%d %H:%M:%S")

# What this workspace IS. Yours to write, once.
#
# Everything else in TRUTH.md is derived from git, but no amount of commit
# history tells a reader what the workspace is for. Drop a memory/OVERVIEW.md in
# and it appears here on every regeneration; leave it out and you get a one-line
# nudge instead of somebody else's project description.
if [ -f "$WORKSPACE/memory/OVERVIEW.md" ]; then
  CPM_OVERVIEW="$(cat "$WORKSPACE/memory/OVERVIEW.md")"
else
  CPM_OVERVIEW="_Write \`memory/OVERVIEW.md\` to describe this workspace. It appears here verbatim._"
fi

cat > "$TRUTH" << 'HEADER'
# Single Source of Truth

> **Auto-generated by [cpm]. Do not edit manually.**
HEADER

echo "> Last updated: $LAST_UPDATED" >> "$TRUTH"

cat >> "$TRUTH" << 'SECTION'
> Regenerate: `./scripts/generate-truth.sh`

## Project Overview

SECTION

# Written outside the heredoc on purpose: the block above is quoted so that
# backticks and $ in the template stay literal, which also means a variable
# inside it would never expand.
printf '%s\n\n' "$CPM_OVERVIEW" >> "$TRUTH"

cat >> "$TRUTH" << 'SECTION'
## Platform Status

| Platform | Branch | Last Commit | Changelogs |
|----------|--------|-------------|------------|
SECTION

for project in "${PROJECTS[@]}"; do
  repo_dir="$WORKSPACE/$project"
  if [ -d "$repo_dir/.git" ]; then
    branch=$(cd "$repo_dir" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")
    last_commit=$(cd "$repo_dir" && git log -1 --date=short --format="%ad: %s" 2>/dev/null || echo "?")
    cl_count=$(ls "$WORKSPACE/memory/changelogs/$project"/*.md 2>/dev/null | wc -l | tr -d ' ')
    echo "| $project | \`$branch\` | $last_commit | $cl_count |" >> "$TRUTH"
  fi
done

echo "" >> "$TRUTH"

# Cross-platform alerts
echo "## Cross-Platform Alerts" >> "$TRUTH"
echo "" >> "$TRUTH"
echo "Changes mentioning shared contracts (Supabase, RevenueCat, Amplitude, deep links, schemas, migrations):" >> "$TRUTH"
echo "" >> "$TRUTH"

KEYWORDS="Supabase|RevenueCat|Amplitude|OneSignal|deep.?link|schema|migration|entitlement|product.?id|event.?name|webhook|API.?key"
FOUND_ALERTS=0

for project in "${PROJECTS[@]}"; do
  cl_dir="$WORKSPACE/memory/changelogs/$project"
  if [ -d "$cl_dir" ]; then
    for f in "$cl_dir"/*.md; do
      [ -f "$f" ] || continue
      if grep -qiE "$KEYWORDS" "$f" 2>/dev/null; then
        title=$(head -1 "$f" | sed 's/^# //')
        fname=$(basename "$f")
        fdate="${fname:0:10}"
        echo "- **$project** ($fdate): $title" >> "$TRUTH"
        FOUND_ALERTS=1
      fi
    done
  fi
done

[ "$FOUND_ALERTS" -eq 0 ] && echo "_No cross-platform alerts found._" >> "$TRUTH"
echo "" >> "$TRUTH"

# Recent activity (7 days)
echo "## Recent Activity (last 7 days)" >> "$TRUTH"
echo "" >> "$TRUTH"

CUTOFF=$(date -v-7d "+%Y-%m-%d" 2>/dev/null || date -d "7 days ago" "+%Y-%m-%d" 2>/dev/null || echo "2026-01-01")
FOUND_ACTIVITY=0

for project in "${PROJECTS[@]}"; do
  cl_dir="$WORKSPACE/memory/changelogs/$project"
  [ -d "$cl_dir" ] || continue
  for f in $(ls -r "$cl_dir"/*.md 2>/dev/null); do
    fname=$(basename "$f")
    fdate="${fname:0:10}"
    if [[ "$fdate" > "$CUTOFF" ]] || [[ "$fdate" == "$CUTOFF" ]]; then
      title=$(head -1 "$f" | sed 's/^# //')
      hash=$(grep "| Hash" "$f" | head -1 | awk -F'|' '{print $3}' | tr -d ' ')
      echo "- **$project** ($fdate, \`$hash\`): $title" >> "$TRUTH"
      FOUND_ACTIVITY=1
    fi
  done
done

[ "$FOUND_ACTIVITY" -eq 0 ] && echo "_No activity in the last 7 days._" >> "$TRUTH"
echo "" >> "$TRUTH"

# Active plans
PLANS_DIR="$WORKSPACE/memory/plans"
if [ -d "$PLANS_DIR" ]; then
  PLAN_FILES=$(ls "$PLANS_DIR"/*.md 2>/dev/null || true)
  if [ -n "$PLAN_FILES" ]; then
    echo "## Active Plans" >> "$TRUTH"
    echo "" >> "$TRUTH"
    echo "Detailed planning docs in \`memory/plans/\` — read before starting related work." >> "$TRUTH"
    echo "" >> "$TRUTH"
    for f in $PLAN_FILES; do
      fname=$(basename "$f")
      title=$(head -1 "$f" | sed 's/^# //')
      status=$(grep -m1 '^\*\*Status:\*\*' "$f" 2>/dev/null | sed 's/^\*\*Status:\*\* //')
      if [ -n "$status" ]; then
        echo "- **[$title](memory/plans/$fname)** — $status" >> "$TRUTH"
      else
        echo "- **[$title](memory/plans/$fname)**" >> "$TRUTH"
      fi
    done
    echo "" >> "$TRUTH"
  fi
fi

# Amplitude feature flags — canonical doc lives at memory/feature_flags.md
# so it survives TRUTH regeneration. Include verbatim if present.
FLAGS_DOC="$WORKSPACE/memory/feature_flags.md"
if [ -f "$FLAGS_DOC" ]; then
  echo "---" >> "$TRUTH"
  echo "" >> "$TRUTH"
  cat "$FLAGS_DOC" >> "$TRUTH"
  echo "" >> "$TRUTH"
fi

# Per-platform details from summaries
echo "---" >> "$TRUTH"
echo "" >> "$TRUTH"
echo "## Per-Platform Summaries" >> "$TRUTH"
echo "" >> "$TRUTH"

for project in "${PROJECTS[@]}"; do
  summary="$SUMMARY_DIR/$project.md"
  if [ -f "$summary" ]; then
    echo "---" >> "$TRUTH"
    echo "" >> "$TRUTH"
    cat "$summary" >> "$TRUTH"
    echo "" >> "$TRUTH"
  fi
done

echo "[cpm] generated TRUTH.md → $TRUTH"
