#!/bin/bash
# Make every skill in skills/ loadable by whichever coding agent you use.
#
# 1. Writes skills/INDEX.md: one line per skill (name, when to use it, path).
#    Any agent can read that file and open the SKILL.md it needs, so skills
#    work even in agents with no skill support of their own.
# 2. Links each skill into the folders agents with native skill loading read.
#    By default that is .claude/skills/ (Claude Code) and .agents/skills/ (the
#    shared folder other agents use). Set CPM_SKILL_DIRS to change the list,
#    e.g. CPM_SKILL_DIRS=".agents/skills .my-agent/skills".
#
# Links are relative, so moving the workspace breaks nothing. A folder in a
# skills dir that is not our link is left alone (it is somebody's own skill),
# and links whose skill was deleted are removed. Folders starting with _ (the
# template) are never linked.
#
#   scripts/link-skills.sh           link, quietly
#   scripts/link-skills.sh --list    link and print what is available

WORKSPACE="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$WORKSPACE/skills"
DIRS="${CPM_SKILL_DIRS:-.claude/skills .agents/skills}"
[ -d "$SRC" ] || exit 0

# ── Index ────────────────────────────────────────────────────
index="$SRC/INDEX.md"
{
  echo "# Skills index"
  echo ""
  echo "Generated by \`scripts/link-skills.sh\`. Before a task that matches a line below,"
  echo "open that skill's \`SKILL.md\` and follow it."
  echo ""
  for dir in "$SRC"/*/; do
    name="$(basename "$dir")"
    case "$name" in _*) continue ;; esac
    [ -f "$dir/SKILL.md" ] || continue
    desc="$(sed -n 's/^description:[[:space:]]*//p' "$dir/SKILL.md" | head -1)"
    echo "- **$name** (\`skills/$name/SKILL.md\`): $desc"
  done
} > "$index.tmp" && mv "$index.tmp" "$index"

# ── Links ────────────────────────────────────────────────────
linked=0
for rel in $DIRS; do
  DEST="$WORKSPACE/$rel"
  up="$(echo "$rel" | awk -F/ '{for (i = 1; i <= NF; i++) if ($i != "") printf "../"}')"
  mkdir -p "$DEST"

  for link in "$DEST"/*; do
    [ -L "$link" ] || continue
    case "$(readlink "$link")" in
      "${up}skills/"*) [ -e "$link" ] || rm -f "$link" ;;
    esac
  done

  for dir in "$SRC"/*/; do
    name="$(basename "$dir")"
    case "$name" in _*) continue ;; esac
    [ -f "$dir/SKILL.md" ] || continue
    target="$DEST/$name"
    if [ -L "$target" ] || [ ! -e "$target" ]; then
      ln -sfn "${up}skills/$name" "$target"
      linked=$((linked + 1))
    fi
  done
done

if [ "$1" = "--list" ]; then
  sed -n 's/^- \*\*\([^*]*\)\*\*.*/  \1/p' "$index"
  echo "skills linked into: $DIRS (index: skills/INDEX.md)"
fi
exit 0
